export const tableDef = {
    "00": {
      value: "00",
      left: null,
      right: null,
      down: "0",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 4,
        colStart: 1,
        colEnd: 2,
      },
      color: "green",
      class: "zero",
    },
    0: {
      value: "0",
      left: null,
      right: null,
      down: null,
      up: "00",
      position: {
        rowStart: 4,
        rowEnd: 7,
        colStart: 1,
        colEnd: 2,
      },
      color: "green",
      class: "zero",
    },
    firstThird: {
      value: "1st 12",
      left: null,
      right: "secondThird",
      down: null,
      up: null,
      position: {
        rowStart: 7,
        rowEnd: 8,
        colStart: 2,
        colEnd: 10,
      },
      color: "green",
      class: "third",
      selectedVals: [1,2,3,4,5,6,7,8,9,10,11,12]
    },
    secondThird: {
      value: "2nd 12",
      left: "firstThird",
      right: "thirdThird",
      down: null,
      up: null,
      position: {
        rowStart: 7,
        rowEnd: 8,
        colStart: 10,
        colEnd: 18,
      },
      color: "green",
      class: "third",
      selectedVals: [13,14,15,16,17,18,19,20,21,22,23,24]
    },
    thirdThird: {
      value: "3rd 12",
      left: "secondThird",
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 7,
        rowEnd: 8,
        colStart: 18,
        colEnd: 26,
      },
      color: "green",
      class: "third",
      selectedVals: [25,26,27,28,29,30,31,32,33,34,35,36]
    },
    firstHalf: {
      value: "1-18",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 2,
        colEnd: 6,
      },
      color: "green",
      class: "half",
      selectedVals: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    },
    even: {
      value: "Even",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 6,
        colEnd: 10,
      },
      color: "green",
      class: "half",
      selectedVals: [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36],
    },
    red: {
      value: "Red",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 10,
        colEnd: 14,
      },
      color: "red",
      class: "half",
      selectedVals: [1,3,5,7,9,12,14,16,18,21,23,25,27,28,30,32,34,36]
    },
    black: {
      value: "Black",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 14,
        colEnd: 18,
      },
      color: "black",
      class: "half",
      selectedVals: [2,4,6,8,10,11,13,15,17,19,20,22,24,26,29,31,33,35]
    },
    odd: {
      value: "Odd",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 18,
        colEnd: 22,
      },
      color: "green",
      class: "half",
      selectedVals: [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35]
    },
    secondHalf: {
      value: "19-36",
      left: null,
      right: null,
      down: null,
      up: null,
      position: {
        rowStart: 8,
        rowEnd: 9,
        colStart: 22,
        colEnd: 26,
      },
      color: "green",
      class: "half",
      selectedVals: [19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]
    },
    firstRow: {
      value: "2-1",
      left: null,
      right: null,
      down: "secondRow",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 26,
        colEnd: 28,
      },
      color: "green",
      class: "row",
      selectedVals: [3,6,9,12,15,18,21,24,27,30,33,36]
    },
    secondRow: {
      value: "2-1",
      left: null,
      right: null,
      down: "thirdRow",
      up: "firstRow",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 26,
        colEnd: 28,
      },
      color: "green",
      class: "row",
      selectedVals: [2,5,8,11,14,17,20,23,26,29,32,35]
    },
    thirdRow: {
      value: "2-1",
      left: null,
      right: null,
      down: null,
      up: "secondRow",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 26,
        colEnd: 28,
      },
      color: "green",
      class: "row",
      selectedVals: [1,4,7,10,13,16,19,22,25,28,31,34]
    },

/**************** NUMBERS ******************/

    3: {
      value: "3",
      left: null,
      right: "6",
      down: "2",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 2,
        colEnd: 4,
      },
      color: "red",
      class: "number",
    },
    6: {
      value: "6",
      left: "3",
      right: "9",
      down: "5",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 4,
        colEnd: 6,
      },
      color: "black",
      class: "number",
    },
    9: {
      value: "9",
      left: "6",
      right: "12",
      down: "8",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 6,
        colEnd: 8,
      },
      color: "red",
      class: "number",
    },
    12: {
      value: "12",
      left: "9",
      right: "15",
      down: "11",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 8,
        colEnd: 10,
      },
      color: "red",
      class: "number",
    },
    15: {
      value: "15",
      left: "12",
      right: "18",
      down: "14",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 10,
        colEnd: 12,
      },
      color: "black",
      class: "number",
    },
    18: {
      value: "18",
      left: "15",
      right: "21",
      down: "17",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 12,
        colEnd: 14,
      },
      color: "red",
      class: "number",
    },
    21: {
      value: "21",
      left: "18",
      right: "24",
      down: "20",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 14,
        colEnd: 16,
      },
      color: "red",
      class: "number",
    },
    24: {
      value: "24",
      left: "21",
      right: "27",
      down: "23",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 16,
        colEnd: 18,
      },
      color: "black",
      class: "number",
    },
    27: {
      value: "27",
      left: "24",
      right: "30",
      down: "26",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 18,
        colEnd: 20,
      },
      color: "red",
      class: "number",
    },
    30: {
      value: "30",
      left: "27",
      right: "33",
      down: "29",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 20,
        colEnd: 22,
      },
      color: "red",
      class: "number",
    },
    33: {
      value: "33",
      left: "30",
      right: "36",
      down: "32",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 22,
        colEnd: 24,
      },
      color: "black",
      class: "number",
    },
    36: {
      value: "36",
      left: "33",
      right: null,
      down: "35",
      up: null,
      position: {
        rowStart: 1,
        rowEnd: 3,
        colStart: 24,
        colEnd: 26,
      },
      color: "red",
      class: "number",
    },
    2: {
      value: "2",
      left: null,
      right: "5",
      down: "1",
      up: "3",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 2,
        colEnd: 4,
      },
      color: "black",
      class: "number",
    },
    5: {
      value: "5",
      left: "2",
      right: "8",
      down: "4",
      up: "6",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 4,
        colEnd: 6,
      },
      color: "red",
      class: "number",
    },
    8: {
      value: "8",
      left: "5",
      right: "11",
      down: "7",
      up: "9",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 6,
        colEnd: 8,
      },
      color: "black",
      class: "number",
    },
    11: {
      value: "11",
      left: "8",
      right: "14",
      down: "10",
      up: "12",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 8,
        colEnd: 10,
      },
      color: "black",
      class: "number",
    },
    14: {
      value: "14",
      left: "11",
      right: "17",
      down: "13",
      up: "15",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 10,
        colEnd: 12,
      },
      color: "red",
      class: "number",
    },
    17: {
      value: "17",
      left: "14",
      right: "20",
      down: "16",
      up: "18",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 12,
        colEnd: 14,
      },
      color: "black",
      class: "number",
    },
    20: {
      value: "20",
      left: "17",
      right: "23",
      down: "19",
      up: "21",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 14,
        colEnd: 16,
      },
      color: "black",
      class: "number",
    },
    23: {
      value: "23",
      left: "20",
      right: "26",
      down: "22",
      up: "24",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 16,
        colEnd: 18,
      },
      color: "red",
      class: "number",
    },
    26: {
      value: "26",
      left: "23",
      right: "29",
      down: "25",
      up: "27",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 18,
        colEnd: 20,
      },
      color: "black",
      class: "number",
    },
    29: {
      value: "29",
      left: "26",
      right: "32",
      down: "28",
      up: "30",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 20,
        colEnd: 22,
      },
      color: "black",
      class: "number",
    },
    32: {
      value: "32",
      left: "29",
      right: "35",
      down: "31",
      up: "33",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 22,
        colEnd: 24,
      },
      color: "red",
      class: "number",
    },
    35: {
      value: "35",
      left: "32",
      right: null,
      down: "34",
      up: "36",
      position: {
        rowStart: 3,
        rowEnd: 5,
        colStart: 24,
        colEnd: 26,
      },
      color: "black",
      class: "number",
    },
    1: {
      value: "1",
      left: null,
      right: "4",
      down: null,
      up: "2",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 2,
        colEnd: 4,
      },
      color: "red",
      class: "number",
    },
    4: {
      value: "4",
      left: "1",
      right: "7",
      down: null,
      up: "5",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 4,
        colEnd: 6,
      },
      color: "black",
      class: "number",
    },
    7: {
      value: "7",
      left: "4",
      right: "10",
      down: null,
      up: "8",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 6,
        colEnd: 8,
      },
      color: "red",
      class: "number",
    },
    10: {
      value: "10",
      left: "7",
      right: "13",
      down: null,
      up: "11",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 8,
        colEnd: 10,
      },
      color: "black",
      class: "number",
    },
    13: {
      value: "13",
      left: "10",
      right: "16",
      down: null,
      up: "14",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 10,
        colEnd: 12,
      },
      color: "black",
      class: "number",
    },
    16: {
      value: "16",
      left: "13",
      right: "19",
      down: null,
      up: "17",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 12,
        colEnd: 14,
      },
      color: "red",
      class: "number",
    },
    19: {
      value: "19",
      left: "16",
      right: "22",
      down: null,
      up: "20",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 14,
        colEnd: 16,
      },
      color: "black",
      class: "number",
    },
    22: {
      value: "22",
      left: "19",
      right: "25",
      down: null,
      up: "23",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 16,
        colEnd: 18,
      },
      color: "black",
      class: "number",
    },
    25: {
      value: "25",
      left: "22",
      right: "28",
      down: null,
      up: "26",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 18,
        colEnd: 20,
      },
      color: "red",
      class: "number",
    },
    28: {
      value: "28",
      left: "25",
      right: "31",
      down: null,
      up: "29",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 20,
        colEnd: 22,
      },
      color: "red",
      class: "number",
    },
    31: {
      value: "31",
      left: "28",
      right: "34",
      down: null,
      up: "32",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 22,
        colEnd: 24,
      },
      color: "black",
      class: "number",
    },
    34: {
      value: "34",
      left: "31",
      right: null,
      down: null,
      up: "35",
      position: {
        rowStart: 5,
        rowEnd: 7,
        colStart: 24,
        colEnd: 26,
      },
      color: "red",
      class: "number",
    },
  };
